void track_init(void);
void track_playStep(int indexStep,int trackIndex);
void track_loop(void);
int track_nextScale(void);
void track_tick1ms(void);
int track_getCurrentTrack(void);
void track_silenceStep(int stepIndex, int trackIndex);
int track_nextTrack(void);
int track_getCurrentStepInTrack(void);
int track_getCurrentScale(void);
